apiVersion: v1
kind: PersistentVolume
metadata:
  name: artifact-volume-pv
  labels:
    app: {{ template "tao-server.name" . }}
spec:
  capacity:
    storage: 64Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: tao-api-sc
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: "{{ .Values.modelRepoGenerator.nfs.path }}/models"
    server: {{ .Values.modelRepoGenerator.nfs.server }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: workdir-pv
  labels:
    app: {{ template "tao-server.name" . }}
spec:
  capacity:
    storage: 64Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: tao-api-sc
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: "{{ .Values.modelRepoGenerator.nfs.path }}/workspace"
    server: {{ .Values.modelRepoGenerator.nfs.server }}