apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: tao-api-sc
  labels:
    app: {{ template "tao-server.name" . }}
provisioner: k8s-sigs.io/nfs-subdir-external-provisioner
parameters:
  pathPattern: "${.PVC.namespace}-${.PVC.name}"
  archiveOnDelete: "false"